# Generated by Django 4.0.6 on 2023-03-13 16:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_portfolio_image_portfolio_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Basic_information',
            field=models.TextField(blank=True, verbose_name='Biography (Age, Language, Location...)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone (+234..........)'),
        ),
    ]
